changelog:
  categories:
    - title: "Breaking Changes"
      labels:
        - "breaking"
    - title: "Features"
      labels:
        - "enhancement"
        - "feature"
    - title: "Bug Fixes"
      labels:
        - "bug"
        - "fix"
    - title: "Security"
      labels:
        - "security"
    - title: "Dependencies"
      labels:
        - "dependencies"
    - title: "Other Changes"
      labels:
        - "*"
  exclude:
    labels:
      - "skip-changelog"
